spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/jibangyoung?useSSL=false&characterEncoding=UTF-8
    username: root
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
