version: "3.8"

services:
  # frontend:
  #   build:
  #     context: ../../ # 현재 위치가 infra/docker라면 root 기준
  #     dockerfile: infra/docker/Dockerfile.frontend
  #   image: jibangyoung-frontend:latest
  #   container_name: jibangyoung-frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - NEXT_PUBLIC_API_URL=http://jibangyoung-backend:8080
  #   depends_on:
  #     - backend
  #   networks:
  #     - jibangyoung-net

  # backend:
  #   build:
  #     context: ../../
  #     dockerfile: infra/docker/Dockerfile.backend
  #   image: jibangyoung-backend:latest
  #   container_name: jibangyoung-backend
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #     - DB_URL=jdbc:mysql://jibangyoung-mysql:3306/jibangyoung
  #     - DB_USER=devuser
  #     - DB_PASSWORD=devpass
  #     - REDIS_HOST=jibangyoung-redis
  #     - REDIS_PORT=6379
  #     - ELASTICSEARCH_HOST=jibangyoung-elasticsearch
  #     - ELASTICSEARCH_PORT=9200
  #     - TZ=Asia/Seoul
  #   depends_on:
  #     - mysql
  #     - redis
  #     - elasticsearch
  #   networks:
  #     - jibangyoung-net

  mysql:
    image: mysql:8.0
    container_name: jibangyoung-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: jibangyoung
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      TZ: Asia/Seoul
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jibangyoung-net

  redis:
    image: redis:7
    container_name: jibangyoung-redis
    ports:
      - "6379:6379"
    networks:
      - jibangyoung-net
    command: ["redis-server", "--appendonly", "yes"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: jibangyoung-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - TZ=Asia/Seoul
    ports:
      - "9200:9200"
    networks:
      - jibangyoung-net

volumes:
  mysql_data:
    driver: local

networks:
  jibangyoung-net:
    driver: bridge
